baseURL = "https://firstdonoharm.dev"
# canonifyURLs = true
languageCode = "en-us"
title = "The Hippocratic License 2.0"
disableKinds = ["RSS"]

DefaultContentLanguage = "en"
hasCJKLanguage = true
EnableMissingTranslationPlaceholders = true

uglyURLs = true

googleAnalytics = "UA-101929377-4"

[mediaTypes]
[mediaTypes."text/markdown"]
suffixes = ["md"]

[mediaTypes."text/plain"]
suffixes = ["txt"]

[outputFormats]
[outputFormats.Markdown]
mediaType = "text/markdown"
isPlainText = true
baseName = "LICENSE"

[outputs]
home = ["html"]
page = ["html", "markdown"]

# Add all translated languages here.
[Languages]
[Languages.en]
languageName = "English"
languageCode = "en"
weight = 1
